feat(catalog): faster root category product count
mage-os/mageos-magento2 pull request #25
Opened 2023-04-08 18:25 UTC by damienwebdev

Previously, in the admin panel, the root scope for the categoryTree was wildly
    slow when there were many `is_anchor` categories. This was due to several bugs:
    
    1: A missing index: `catalog_category_product_index` that is defunct and was
    replaced by `catalog_category_product_index_store*` however, this table
    did not exist for the `store0`. This table adds that index.
    
    2. A bad computation of the `rootCategoryIds` for the root store, causing
    a bad where clause on a join against the temporary category recursion table.
    
    3. An extremely poor perfomance private method (getProductsCountFromCategoryTable)
    which should not have been merged in the first place given how slow it is.
    
    This does cause a small UX bug when the index is empty. The category page will show
    0 products instead of performing the computation. This should be an acceptable break,
    given how slow it is to attempt to compute these values manually.

2023-04-08 18:47 UTC, damienwebdev commented
@Vinai I think the semver check is broken. Additionally, I have no idea how to write tests for this, I have no idea wtf to do with the temp table/indexer changes I made. Debugging this was a nightmare. @vitaliy-golomoziy

2023-10-05 20:27 UTC, Vinai commented
Thanks @damienwebdev - I agree the semver check seems to be broken. Probably we should disable it until we have the resources.

It would be great if you could push an empty commit to this PR so it triggers the current set of checks. I can't force a run manually myself.

2023-10-07 18:12 UTC, Vinai requested changes

2023-10-07 18:12 UTC, Vinai commented on app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
> +        $this->tableMaintainer = \Magento\Framework\App\ObjectManager::getInstance()->get(TableMaintainer::class);
Out of curiosity, why is the `TableMaintainer` dependency not added as a constructor argument in the same way as the `Visibility` instance?

2023-10-07 18:12 UTC, Vinai commented on app/code/Magento/Catalog/Model/ResourceModel/Category/Collection.php
> +                    : 0;
I would like to have a comment here noting the `0` will be used when the index hasn't been built yet.  
The PR notes explained it nicely, but I can imagine someone (me?) stumbling over this in future and wondering about the reasoning behind it.

2023-10-07 18:19 UTC, Vinai approved these changes

2023-10-07 18:20 UTC, Vinai commented
I'll approve the changes and merge them despite my two small comments, as I've gone over the patch and understand what it does and tried it out locally.

2023-10-07 18:21 UTC, merged